language: python

sudo: required

#Pre-install packages for the ubuntu distribution
cache:
  apt: true
  directories:
  - $HOME/.cache/pip
  - $HOME/download

env:
    - NIBABEL=test

python:
    - "3.7"

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p $HOME/miniconda
  - source $HOME/miniconda/bin/activate root
  - conda update --yes conda

# Install packages
install:
    - conda install --yes python=$TRAVIS_PYTHON_VERSION scipy
    - pip install "numpy~=1.6" "setuptools>=42.0.2" "wheel>=0.33.6" "cython>=0.29" "scikit-learn~=0.22" "pandas>=1.0.1"
    - pip install "joblib>=0.14.1"
    - pip install seaborn
    - pip install nose
    - pip install codecov
    - python setup.py build_ext --inplace

# command to run tests
script:
    - nosetests -v --with-coverage
    - codecov -t 85b26c32-8e30-4dd5-b07c-64cff0361d63