[build-system]
requires = [
    'setuptools>=42.0.2',
    'wheel>=0.33.6',
    'numpy~=1.6',
    'cython>=0.29',
    'scikit-learn~=0.22',
    'pandas>=1.0.1',
    'joblib>=0.14.1'
]
build-backend = "setuptools.build_meta"
